-- AlterTable
ALTER TABLE "Track" ALTER COLUMN "speechiness" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "energy" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "UserGenrePreference" ALTER COLUMN "speechiness" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "energy" SET DATA TYPE DECIMAL(65,30);
